dist: xenial
language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - libjansson-dev
      - awscli
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
cache:
  directories:
    - ${TRAVIS_HOME}/.cargo
before_cache:
  - rm -rf ${TRAVIS_HOME}/.cargo/registry
services: docker
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      script: cargo test
    - stage: check
      name: Rustfmt
      install: rustup component add rustfmt-preview
      script: cargo fmt -- --check
    - stage: check
      name: Clippy
      install: rustup component add clippy-preview
      script: cargo clippy
    - stage: deploy
      name: Docs
      install: cargo install mdbook --vers 0.2.3 --force
      script: mdbook build docs && ./deploy.init.sh && PROJECT='janus-conference' ./deploy/s3-docs.sh
stages:
  - name: check
  - name: deploy
notifications:
  email: false
env:
  global:
    APP_UPLOADING_YANDEX_ACCESS_KEY_ID: "12345"
    APP_UPLOADING_YANDEX_SECRET_ACCESS_KEY: "secret"
    APP_UPLOADING_YANDEX_ENDPOINT: "https://storage.yandexcloud.net"
    APP_UPLOADING_YANDEX_REGION: "ru-central1"
