apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: netologygroup/janus-gateway
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{ .IMAGE_NAME }}:{{ .IMAGE_TAG }}'
  local:
    push: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - k8s/janus-gateway.yaml
    - k8s/janus-gateway-service.yaml
