apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_NAME }}:{{ .IMAGE_TAG }}"
  artifacts:
    - image: netologygroup/janus-gateway
      docker:
        dockerfile: docker/Dockerfile.deploy
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - k8s/janus-gateway.yaml
