[general]
vacuum_interval = 60

[recordings]
enabled = true
directory = "/recordings"
delete_records = true

[constraint.writer.video]
default_remb = 300000
max_remb = 1000000

[constraint.writer.audio]
default_remb = 30000
max_remb = 60000

[upload]
backends = ["yandex"]
