[general]
vacuum_interval = 60

[recordings]
enabled = true
directory = "/recordings"
delete_records = true

[constraint.writer]
default_video_bitrate = 300000
max_video_remb = 1000000
audio_bitrate = 30000

[upload]
backends = ["yandex"]
