apiVersion: v1
kind: Service
metadata:
  name: janus-gateway-service
spec:
  # Required in order to bind specific Janus Gateway service to
  # particular node network interface via externalIPs.
  type: NodePort
  # TODO: automate?
  externalIPs:
    - 1.2.3.4
  # Disable any traffic forwarding further into the cluster since
  # we are bound to specific node and should preserve source IPs.
  externalTrafficPolicy: Local
  selector:
    app: janus-gateway
  # TODO: we need a way to specify ~ 1000-2000 ports somehow.
  ports:
    - port: 30000
      targetPort: 30000
      protocol: UDP
    - port: 30001
      targetPort: 30001
      protocol: UDP
    - port: 30002
      targetPort: 30002
      protocol: UDP
    - port: 30003
      targetPort: 30003
      protocol: UDP
