version: '3'
services:
  janus:
    build:
      context: ..
      dockerfile: ./docker/develop.dockerfile
    ports:
      - "2000:2000"               # gdbserver
      - "7088:7088"               # HTTP transport
      - "8188:8188"               # WebSocket transport
      - "30000-31000:30000-31000" # WebRTC UDP
    volumes:
      - ..:/build
      - ../recordings:/recordings
      - janus-conference-cargo:/usr/local/cargo
      - ../scripts/upload_record.sh:/opt/janus/bin/upload_record.sh
      - ../../janus-conference-logger:/logger
    env_file: janus.plugin.conference.environment
    links:
      - vernemq
    platform: linux/x86_64
    working_dir: /build
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
  vernemq:
    image: cr.yandex/crp1of6bddata8ain3q5/mqtt-gateway:v0.13.7
    ports:
      - "1883:1883"
      - "8080:8080"
    environment:
      APP_AUTHN_ENABLED: 0
      APP_AUTHZ_ENABLED: 0
      APP_STAT_ENABLED: 0
      APP_DYNSUB_ENABLED: 1
      APP_RATE_LIMIT_ENABLED: 0
      APP_AGENT_LABEL: alpha
      APP_ACCOUNT_ID: mqtt-gateway.dev.svc.example.org
volumes:
  janus-conference-cargo: {}
